$ ->
	if ! window.$cf?
		window.$cf = {}

	##################################################################################
	# Car Makes
	##################################################################################
	$cf.makes = [
		"Abarth",
		"AC",
		"Alfa Romeo",
		"Aston Martin",
		"Audi",
		"Austin",
		"Beauford",
		"Bentley",
		"BMW",
		"Cadillac",
		"Chevrolet",
		"Chrysler",
		"Citroen",
		"Dacia",
		"Daewoo",
		"Daihatsu",
		"Daimler",
		"Datsun",
		"Dodge",
		"Ferrari",
		"Fiat",
		"Ford",
		"Gwm",
		"Hillman",
		"Honda",
		"Humber",
		"Hummer",
		"Hyundai",
		"Isuzu",
		"Jaguar",
		"Jeep",
		"Jensen",
		"KIA",
		"Lancia",
		"Land Rover",
		"Lexus",
		"Lincoln",
		"Lola",
		"Lotus",
		"Maserati",
		"Mazda",
		"Mercedes-Benz",
		"MG",
		"MINI",
		"Mitsubishi",
		"Morgan",
		"Morris",
		"Nissan",
		"NSU",
		"Opel",
		"Panther",
		"Perodua",
		"Peugeot",
		"Porsche",
		"Proton",
		"Reliant",
		"Renault",
		"Rolls-Royce",
		"Rover",
		"Saab",
		"SEAT",
		"Skoda",
		"Smart",
		"Ssangyong",
		"Subaru",
		"Suzuki",
		"Tata",
		"Toyota",
		"Triumph",
		"TVR",
		"Vauxhall",
		"Volkswagen",
		"Volvo",
		"Wolseley"
	];

	$cf.financial_institutions = [
		"ACC BANK",
		"ANGLO-IRISH BANKCORP",
		"AIB BANK PLC",
		"BOI FINANCE",
		"BANK OF IRELAND",
		"CANADA LIFE",
		"CALEDONIAN ASS.",
		"CREDIT UNION",
		"EBS",
		"FIRST NATIONAL B.S.",
		"GOODBODY S/BROKERS",
		"ICC",
		"IR CIVIL SERVICE B.S.",
		"IRISH LIFE ASSURANCE",
		"IRISH LIFE B.S.",
		"IRISH NATIONWIDE B.S",
		"IRISH PERMANENT B.S.",
		"LOCAL AUTHORITY",
		"LIFETIME",
		"LOMBARD &amp; ULSTER",
		"MISCELLANEOUS",
		"NCB GROUP",
		"NIB/NORTHERN BANK",
		"NORWICH IRISH B.S.",
		"NEW IRELAND ASS.",
		"NORWICH UNION ASS.",
		"OTHER STOCKBROKERS",
		"OTHER STATE INST.",
		"OTHER BANKS",
		"OTH FINANCE/LEASING",
		"OTH LIFE ASSURANCE",
		"OTH BLD. SOCIETIES",
		"PREMIER BANKING",
		"POST OFFICE",
		"PRU LIFE ASSURANCE",
		"RIADA &amp; CO",
		"SMURFIT FINANCE",
		"SOLOMONS",
		"STANDARD LIFE ASS.",
		"STATE INSTITUTIONS",
		"TSB BANK",
		"ULSTER BANK",
		"UNKNOWN",
		"WOODCHESTER BANK"
	];